def get_exception
  1/0
rescue => e
  e
end
